CREATE ROLE caso2 WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '12345678';

CREATE DATABASE caso2
    WITH 
    OWNER = caso2
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;